swagger: '2.0'
info:
  version: 1.0.0
  title: 'SOAP services API'

schemes:
- http
- https

basePath: /

paths:
  /gas:
    post:
      tags:
      - Pay invoice
      operationId: payGasInvoice
      parameters:
      - name: invoice
        in: body
        type: object
        required: true
        schema:
          $ref: './entities/invoice.json'
      responses:
        200:
          description: 'Gas invoice payed'
        400:
          description: 'Error on pay'
    patch:
      tags:
      - Compensate invoice
      operationId: compensateGasInvoice
      parameters:
      - name: invoice
        in: body
        type: object
        required: true
        schema:
          $ref: './entities/invoice.json'
      responses:
        200:
          description: 'Invoice compensation OK'
        400:
          description: 'Error on compensation'
  /gas/{invoice}:
    get:
      tags:
      - Get invoice
      operationId: getGasInvoice
      parameters:
      - name: invoice
        in: path
        type: string
        required: true
      responses:
        200:
          description: 'Get information of invoice'
          schema:
            $ref: './entities/invoice.json'