version: '3'
services:
  client-service:
    build: client-service
    ports:
    - "8081:8080"
  mailhog:
    image: mailhog/mailhog
    ports:
    - "1025:1025"
    - "8025:8025"
  notification-service:
    build: notifications-service
    ports:
    - "8082:8080"
    depends_on:
      - mailhog
