version: '3'
services:
  registry:
    build: inventory-service
    ports:
    - "8761:8761"
    expose:
    - "8761"
  client-service:
    build: client-service
    ports:
    - "8081:8080"
    depends_on:
    - registry
  mailhog:
    image: mailhog/mailhog
    ports:
    - "1025:1025"
    - "8025:8025"
  notification-service:
    build: notifications-service
    ports:
    - "8082:8080"
    depends_on:
      - mailhog
      - registry
  soap-gas-service:
    build: soap-consumer-service
    ports:
    - "8083:8080"
    depends_on:
    - registry

