version: '3'
services:
  client-service:
    build: client-service
    ports:
    - "8081:8080"
    networks:
    - aes-workshop
  mailhog:
    image: mailhog/mailhog
    ports:
    - "1025:1025"
    - "8025:8025"
    networks:
    - aes-workshop
  notification-service:
    build: notifications-service
    ports:
    - "8082:8080"
    depends_on:
      - mailhog
    networks:
    - aes-workshop
  soap-gas-service:
    build: soap-consumer-service
    ports:
    - "8083:8080"
    networks:
    - aes-workshop

networks:
  aes-workshop:
    driver: bridge

