version: '2.2'
services:
  zookeeper:
    image: wurstmeister/zookeeper:3.4.6
    ports:
    - "2181:2181"
  kafka:
    image: wurstmeister/kafka:2.11-2.0.0
    links:
    - zookeeper
    environment:
      KAFKA_ADVERTISED_HOST_NAME: kafka
      KAFKA_ADVERTISED_PORT: 9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CREATE_TOPICS: "clients:5:1"
  registry:
    build: inventory-service
    ports:
    - "8761:8761"
    expose:
    - "8761"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://host.docker.internal:8761"]
      interval: 10s
      timeout: 10s
      retries: 5
  client-service:
    build: client-service
    ports:
    - "8081:8080"
    depends_on:
      registry:
        condition: service_healthy
    links:
    - kafka
  mailhog:
    image: mailhog/mailhog
    ports:
    - "1025:1025"
    - "8025:8025"
  notification-service:
    build: notifications-service
    ports:
    - "8082:8080"
    depends_on:
      registry:
        condition: service_healthy
      mailhog:
        condition: service_started
    links:
    - kafka
  soap-gas-service:
    build: soap-consumer-service
    ports:
    - "8083:8080"
    depends_on:
      registry:
        condition: service_healthy

